name: ai_providers_example
description: A stunning demo app showcasing all AI Providers SDK capabilities
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Our AI Providers SDK (local path for development)
  ai_providers:
    path: ../
  
  # UI & Animations
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.4
  flutter_animate: ^4.5.0
  
  # Environment variables
  flutter_dotenv: ^6.0.0
  
  # File handling & image processing
  file_picker: ^8.1.5
  image: ^4.3.0
  
  # Development
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/ai_providers_config.yaml