name: ai_providers
description: Unified AI provider integration for Flutter - OpenAI, Google AI, xAI, Android native TTS with consistent API.
version: 1.4.3
homepage: https://github.com/albertooishii/ai_providers
repository: https://github.com/albertooishii/ai_providers
issue_tracker: https://github.com/albertooishii/ai_providers/issues
license: MPL-2.0
documentation: https://github.com/albertooishii/ai_providers#readme

# Professional metadata for pub.dev
topics:
  - ai
  - flutter
  - openai
  - llm
  - sdk

# Platform support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core HTTP and networking
  http: ^1.1.0
  
  # Utilities
  crypto: ^3.0.3
  path: ^1.8.3
  
  # Storage and preferences  
  shared_preferences: ^2.2.2
  
  # Audio capabilities
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0
  record: ^6.1.1
  audioplayers: ^6.1.0
  
  # Storage and preferences
  path_provider: ^2.1.1
  
  # Configuration
  yaml: ^3.1.2
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.26.2
  flutter_lints: ^6.0.0

# Pub.dev screenshot and funding info
